language: python

dist: trusty

python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

git:
  depth: 3

install:
  - pip3 install bitarray

script:
  - wget "http://diego.assencio.com" -O file.txt
  - ./huffman -c file.txt > file.bin
  - ./huffman -d file.bin > file_original.txt
  - diff file.txt file_original.txt

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
